name: CI Jenkins-CX Branch Pipeline

on:
  push:
    branches:
      - feature/*
      - fix/*
      - bugfix/*

jobs:
  build:
    name: CI Jenkins-CX Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: check env
        run: |
          set
      - name: get version number
        run: |
          chmod 777 mvnw
          ./mvnw help:evaluate -Dexpression=project.version -Doutput=.version -s '.mvn/wrapper/settings.xml'
          cat .version | cut -d'-' -f 1 > .version
      - name: Build & Test Groovy
        run: |
          bash build/maven/mvn-install.sh .
        env:
          MAVEN_REPOSITORY: '.m2/repository'
      - name: Build Docker
        run: |
          bash  build/docker/docker-build.sh .
      - name: set version
        run: |
          ./mvnw versions:set -DnewVersion="$(cat .version)" -s '.mvn/wrapper/settings.xml'
      - name: Create GH Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: $(cat .version)
          release_name: Release $(cat .version)
          body: |
            $(cat CHANGELOG.md)
          draft: false
          prerelease: false