name: CI Jenkins-CX

on:
  push:
    branches:
      - master
      - feature/*
      - fix/*
      - bugfix/*

jobs:
  build:
    name: CI Jenkins-CX
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          export MAVEN_REPOSITORY=.m2/repository
          sh .build/maven/mvn-package.sh .