name: CI Jenkins-CX Release Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: CI Jenkins-CX Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: check env
        run: |
          set
      - name: get version number
        run: |
          bash build/maven/mvn-get-release-version.sh . '.m2/repository'
      - name: Build & Test
        run: |
          bash build/maven/mvn-install.sh . '.m2/repository'
      - name: Build Docker
        run: |
          bash  build/docker/docker-build.sh .
      - name: Build & Test & Upload
        run: |
          bash build/maven/mvn-deploy.sh . '.m2/repository' x-access-token ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GH Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/master')
        with:
          body_path: RELEASE.md
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
