name: CI Jenkins-CX Release Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: CI Jenkins-CX
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: create version number
        run: |
          echo $(echo $GITHUB_SHA | cut -c1-7) > .version
      - name: Build & Test
        run: |
          bash build/maven/mvn-install.sh . '.m2/repository'
        env:
          MAVEN_REPOSITORY: '.m2/repository'
      - name: set version
        run: |
          ./mvnw versions:set -DnewVersion="$(cat .version)" -s '.mvn/wrapper/settings.xml'
      - name: upload artifact
        run: |
          bash build/maven/mvn-deploy.sh . '.m2/repository'
        env:
          MAVEN_REPOSITORY: '.m2/repository'
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}